#!/bin/bash
#SBATCH --mem-per-cpu=64G
#SBATCH -J Map 
#SBATCH -o job_logs/Map-%j.out 
#SBATCH -e job_logs/Map-%j.err 
#SBATCH -N 1              
#SBATCH --ntasks-per-node=1              
#SBATCH -t 0-10:00:00
#SBATCH --mail-type=END
#SBATCH --gres=gpu:V100:1    

module load anaconda3/latest
. $ANACONDA_HOME/etc/profile.d/conda.sh

conda activate pytorch
echo $CONDA_DEFAULT_ENV
python --version
python3  simple_DRLMAPF.py

conda deactivate