#!/bin/bash

#SBATCH -J mapf
#SBATCH --gres=gpu:V100:1 # select a host with a Volta GPU
#SBATCH -o job_logs/mapf-%j.out
#SBATCH -e job_logs/mapf-%j.err
#SBATCH -t 1:00:00
#SBATCH --mail-type=END      # an email is sent at the end of the job

  


module purge
module load anaconda3/latest
. $ANACONDA_HOME/etc/profile.d/conda.sh

conda activate pytorch

python3 /home/noushad/Master_thesis/my_PRIMAL/simple_DRLMAPF.py

conda deactivate